version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_production:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: aig3c/rosbank_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_production:/app/media
    depends_on:
      - db

  frontend:
    image: aig3c/rosbank_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: aig3c/rosbank_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_volume:/static
      - media_production:/app/media
      - ./frontend/build:/usr/share/nginx/html/
    depends_on:
      - db
      - backend
